### ISSUE TITLE
GitHub Repositories is deprecated 

### ISSUE THREAD

**Issue by jcreech72** [denisecase/streaming-01-getting-started#1]
GitHub Pull Requests and Issues is the new suggested for install.

**Comment by denisecase** [comment]
Nice work - I saw something about that, but can't find a current source. Reading up on the links below, they both seem active. 

For now, I'll recommend if you have experience (or want to be up on the most powerful options), use Pull Requests and Issues. 

For people new to programming, Git, and Python, I'll recommended getting started with Repositories.

- GitHub Repositories: https://marketplace.visualstudio.com/items?itemName=github.remotehub
- GitHub Pull Requests and Issues: https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github

---- 

Please update your fork to reflect the changes above. Also - there's an update needed to get the examples working on Windows (to keep from writing a blank line after each record).

Thanks for the early review!
